[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["prisma/**"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["anonymous"]}

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  DATABASE_URL = "postgresql://postgres:Vidhi%402605@db.wpgjwynemtgrtjhwgvin.supabase.co:5432/postgres"
  NEXT_PUBLIC_API_URL = "https://moodyss.netlify.app/api"
