[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "18" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[functions]
  included_files = ["node_modules/.prisma/**", "node_modules/@prisma/**", "prisma/**"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

